integers = [ 
    1, 
    2, 
    3 
] # comment

ola = ''' fWJIFEIFEFERIGRE
EJFIOERJEOIW~~
fwefifjfiof
dwewemfif
dwkfowef
'''

key = { efieui }

physical.shape = "round"
site."google.com" = true

name = { first = "Tom", last = "Preston-Werner" }

= "no key name"

[ key ]
physical.shape = "round"
site."google.com" = true

physical.shape = "round"
