# This is a full-line comment

title = "fdsfa" 

[table]

name = "toml"
yey = 12
telmo.olar = 11234


turco = {chines.ola.oee = 1, port.ole = 5, holanda = 3}

[yws]
coord.a.h = "x"

[egrtjg]



[fruit.ola.ole]
apple.color = "red"

[fruit.ola.ole.oli]
apple.color = "green"
